services:
  dsquare_webpage_axum_server_container:
    #build: .
    image: dsquare_webpage_docker:1.0
    env_file: .env
    ports:
      - '${AXUM_SERVER_PORT}:8090'
    environment:
      - RUST_LOG=info
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8090/']
      interval: 30s
      timeout: 10s
      retries: 3
